name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source tree
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Install basic packages that are required for tests
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3-pip python3-setuptools libsystemd-dev

    - name: Install Dependencies
      run: |
        pip install -r requirements-test.txt

    - name: Execute tests
      run: |
        python3 -m pytest .
