name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source tree
      uses: actions/checkout@v2

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Run make devbox-shell
      working-directory: ./csp-cwp-common
#      This is a WA for the problem where actions don't allow container TTY with error: 'the input device is not a TTY'
      shell: 'script -q -e -c "bash {0}"'
      run: |
        make devbox-shell CMD='"make all"'

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: master # The branch the action should deploy to.
        folder: csp-cwp-common/artifacts/coverage/ # The folder the action should deploy.

